# Generated by Django 3.1.7 on 2021-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0003_auto_20210318_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
